[package]
name = "xl-lsp"
version.workspace = true
edition.workspace = true

[dependencies]
async-lsp = { version = "0.2.4", default-features = false, features = ["stdio", "tokio"] }
futures = "0.3"
serde = "1"
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt", "sync"] }
tokio-util = { version = "0.7", features = ["compat"] }
tower-service = "0.3"
xl = { path = "../xl" }

