CREATE TABLE consumers(id INTEGER PRIMARY KEY, household_id INTEGER, region_hint TEXT);
CREATE TABLE households(id INTEGER PRIMARY KEY, address_id INTEGER);
CREATE TABLE addresses(id INTEGER PRIMARY KEY, region_id INTEGER, city TEXT);
CREATE TABLE regions(id INTEGER PRIMARY KEY, name TEXT);
CREATE TABLE sessions(id INTEGER PRIMARY KEY, consumer_id INTEGER, campaign_id INTEGER, started_at TEXT);
CREATE TABLE carts(id INTEGER PRIMARY KEY, consumer_id INTEGER, session_id INTEGER);
CREATE TABLE cart_items(id INTEGER PRIMARY KEY, cart_id INTEGER, product_id INTEGER, quantity INTEGER);
CREATE TABLE orders(id INTEGER PRIMARY KEY, consumer_id INTEGER, session_id INTEGER, ordered_at TEXT, total_cents INTEGER);
CREATE TABLE order_items(id INTEGER PRIMARY KEY, order_id INTEGER, product_id INTEGER, quantity INTEGER, amount_cents INTEGER);
CREATE TABLE products(id INTEGER PRIMARY KEY, category_id INTEGER, sku TEXT);
CREATE TABLE categories(id INTEGER PRIMARY KEY, name TEXT);
CREATE TABLE campaigns(id INTEGER PRIMARY KEY, name TEXT, channel TEXT);
